### ISSUE TITLE
Remover site empacotado

### ISSUE THREAD

**Issue by vaporwavie** [viniciusvts/viniciusvts.github.io#3]
Somente isso deveria estar em seu repositório:

![image](https://user-images.githubusercontent.com/11232965/30820379-20537d4a-a1f8-11e7-8f24-27c41f0f0781.png)

**Sugestão**: O repositório abriga o arcabouço do site *e também* o site empacotado. É recomendado em repositórios de site código aberto, que você mantenha somente a construção do site, já que ele é facilmente configurado e levantado (npm i, ionic serve). Isso evitará pushes longos e sujeira no seu repositório.

**Comment by viniciusvts** [comment]
O site está nesse repósitório porque utiliza o githubpages. Para cumprir essa observação, o projeto do site será movido para: https://github.com/viniciusvts/vtsantana , e o site compilado ficará aqui
