### ISSUE TITLE
Adicionar instruções de instalação no README

### ISSUE THREAD

**Issue by vaporwavie** [viniciusvts/viniciusvts.github.io#4]
Se um usuário se interessar pela sua página e quiser contribuir, como ele fará? É interessante ter instruções de configuração do ambiente localmente, e etc. Afinal de contas, cada projeto tem sua discrepância :D

**Comment by viniciusvts** [comment]
Obrigado @vaporwavie , tenho aprendido muito contigo
o repositório foi movido para: https://github.com/viniciusvts/vtsantana 
O site está nesse repósitório porque utiliza o githubpages, por isso o projeto foi movido
